### PR TITLE
fix sabotage 

### PR DESCRIPTION
**Pull request by viving11**

### CODE REVIEW

**Comment by haleygreenspan** [comment]
All tests passed

**Review by bhegde8 — APPROVED** [review]
Looks good to me. All tests also pass. The sabotages appear to be fixed.

**Review by SR02019 — APPROVED** [review]
The sabotages from my methods appear to be fixed and all the tests that we created passed. Approved.

**Review by xueweiji — APPROVED** [review]
Looks good. Thanks for fixing it.

**Review by apancorb — APPROVED** [review]

**Pull request merged**
